/////////////// L O C A L    H O S T ///////////////
////////////////////////////////////////////////////

// -----------------
// --  READERS  --
// -----------------

### Get all readers
GET http://localhost:3000/readers 


### Get reader by id
GET http://localhost:3000/readers/65b2a0c24f3d9d1a472520fc


### Get reader by NAME
GET http://localhost:3000/readers/name/one&twos


### Create reader
POST http://localhost:3000/readers HTTP/1.1
content-type: application/json 

{
    "ISBN": "9781705024867",
    "format": "Audiobook",
    "author": "Steel, Danielle",
    "title": "The high notes",
    "audience": "Adult",
    "publicationDate": "2022",
    "summary": "Iris Cooper has been singing ever since she can remember, hitting the high notes like no one else. When she is twelve, her father convinces the owner of a bar in Lake City, Texas, to let her perform, and she stuns the audience.",
    "language": "English",
    "subject": "Country musicians, Fathers and daughters",
    "rentalTimeInWeeks": "1"
}


### PUT reader
PUT http://localhost:3000/readers/65b5be0f6751d47f7eafdf8b HTTP/1.1
content-type: application/json

{
    "ISBN": "9781508287605",
    "format": "test",
    "author": "Kingsbury, Karen",
    "title": "The Baxters",
    "audience": "Adult fiction",
    "publicationDate": "2022",
    "summary": "itititititititititit.",
    "language": "English",
    "subject": "TESTit",
    "rentalTimeInWeeks": "1"
}


### DELETE reader
DELETE http://localhost:3000/readers/65b5be0f6751d47f7eafdf8b HTTP/1.1




/////////////// P R O D U C T I O N ///////////////
///////////////////////////////////////////////////

// -----------------
// --  READERS  --
// -----------------

### Get all readers
GET https://cse341-project2-ykx8.onrender.com/readers


### Get reader by id
GET https://cse341-project2-ykx8.onrender.com/readers/65b1d0f6525bba6756f966f9


### Get reader by format
GET https://cse341-project2-ykx8.onrender.com/readers/format/book


### Create reader
POST https://cse341-project2-ykx8.onrender.com/readers HTTP/1.1
content-type: application/json

{
    "ISBN": "9781508287605",
    "format": "Audiobook",
    "author": "Kingsbury, Karen",
    "title": "The Baxters",
    "audience": "Adult fiction",
    "publicationDate": "2022",
    "summary": "A terrible storm builds in the morning sky over Bloomington, Indiana, as Elizabeth Baxter prepares to celebrate her daughter Kari's wedding to Tim Jacobs. It's supposed to be a happy day, but Elizabeth can't shake a growing sense of dread. Something bad is about to happen. Elizabeth knows it.",
    "language": "English",
    "subject": "Weddings, Man-woman relationships, Families, Omens, Bloomington",
    "rentalTimeInWeeks": "1 week"
}


### PUT reader
PUT https://cse341-project2-ykx8.onrender.com/readers/65b1d0f6525bba6756f966f9 HTTP/1.1
content-type: application/json

{
    "ISBN": "9781508287605",
    "format": "Audiobook",
    "author": "Kingsbury, Karen",
    "title": "The Baxters",
    "audience": "Adult fiction",
    "publicationDate": "2022",
    "summary": "A terrible storm builds in the morning sky over Bloomington, Indiana, as Elizabeth Baxter prepares to celebrate her daughter Kari's wedding to Tim Jacobs. It's supposed to be a happy day, but Elizabeth can't shake a growing sense of dread. Something bad is about to happen. Elizabeth knows it.",
    "language": "English",
    "subject": "Weddings, Man-woman relationships, Families, Omens, Bloomington",
    "rentalTimeInWeeks": "1 week"
}


### DELETE reader
DELETE https://cse341-project2-ykx8.onrender.com/readers/65b1d0f6525bba6756f966f9 HTTP/1.1