/////////////// L O C A L    H O S T ///////////////
////////////////////////////////////////////////////

// -----------------
// --  MATERIALS  --
// -----------------

### Get all materials
GET http://localhost:3000/materials 


### Get material by id
GET http://localhost:3000/materials/65b2a8b0bcbcb9a9d5e5858b


### Get material by format
GET http://localhost:3000/materials/format/book


### Get author by material ID
GET http://localhost:3000/materials/author/65b2d656b063639fe610bd6c


### Create material
POST http://localhost:3000/materials HTTP/1.1
content-type: application/json 

{
    "ISBN": "9781705024867",
    "format": "Audiobook",
    "authorId": "009",
    "title": "The high notes",
    "audience": "Adult",
    "publicationDate": "2022",
    "summary": "Iris Cooper has been singing ever since she can remember, hitting the high notes like no one else. When she is twelve, her father convinces the owner of a bar in Lake City, Texas, to let her perform, and she stuns the audience.",
    "language": "English",
    "subject": "Country musicians, Fathers and daughters",
    "rentalTimeInWeeks": "1"
}


### PUT material
PUT http://localhost:3000/materials/65bab937dcedefaed0364f7f HTTP/1.1
content-type: application/json

{
    "ISBN": "9781508287605",
    "format": "test",
    "authorId": "010",
    "title": "The Baxters",
    "audience": "Adult fiction",
    "publicationDate": "2022",
    "summary": "itititititititititit.",
    "language": "English",
    "subject": "TESTit",
    "rentalTimeInWeeks": "1"
}


### DELETE material
DELETE http://localhost:3000/materials/65bab937dcedefaed0364f7f HTTP/1.1




/////////////// P R O D U C T I O N ///////////////
///////////////////////////////////////////////////

// -----------------
// --  MATERIALS  --
// -----------------

### Get all materials
GET https://cse341-project2-ykx8.onrender.com/materials


### Get material by id
GET https://cse341-project2-ykx8.onrender.com/materials/65b1d0f6525bba6756f966f9


### Get material by format
GET https://cse341-project2-ykx8.onrender.com/materials/format/book


### Create material
POST https://cse341-project2-ykx8.onrender.com/materials HTTP/1.1
content-type: application/json

{
    "ISBN": "9781508287605",
    "format": "Audiobook",
    "author": "Kingsbury, Karen",
    "title": "The Baxters",
    "audience": "Adult fiction",
    "publicationDate": "2022",
    "summary": "A terrible storm builds in the morning sky over Bloomington, Indiana, as Elizabeth Baxter prepares to celebrate her daughter Kari's wedding to Tim Jacobs. It's supposed to be a happy day, but Elizabeth can't shake a growing sense of dread. Something bad is about to happen. Elizabeth knows it.",
    "language": "English",
    "subject": "Weddings, Man-woman relationships, Families, Omens, Bloomington",
    "rentalTimeInWeeks": "1 week"
}


### PUT material
PUT https://cse341-project2-ykx8.onrender.com/materials/65b1d0f6525bba6756f966f9 HTTP/1.1
content-type: application/json

{
    "ISBN": "9781508287605",
    "format": "Audiobook",
    "author": "Kingsbury, Karen",
    "title": "The Baxters",
    "audience": "Adult fiction",
    "publicationDate": "2022",
    "summary": "A terrible storm builds in the morning sky over Bloomington, Indiana, as Elizabeth Baxter prepares to celebrate her daughter Kari's wedding to Tim Jacobs. It's supposed to be a happy day, but Elizabeth can't shake a growing sense of dread. Something bad is about to happen. Elizabeth knows it.",
    "language": "English",
    "subject": "Weddings, Man-woman relationships, Families, Omens, Bloomington",
    "rentalTimeInWeeks": "1 week"
}


### DELETE material
DELETE https://cse341-project2-ykx8.onrender.com/materials/65b1d0f6525bba6756f966f9 HTTP/1.1