/////////////// L O C A L    H O S T ///////////////
////////////////////////////////////////////////////

// -----------------
// --  MATERIALS  --
// -----------------

### Get all materials
GET http://localhost:3000/materials


### Get material by id
GET http://localhost:3000/materials/65b2a0c24f3d9d1a472520fc


### Get material by format
GET http://localhost:3000/materials/format/book


### Create material
POST http://localhost:3000/materials HTTP/1.1
content-type: application/json 

{
    "ISBN": "9781534462540",
    "format": "Book123",
    "author": "Stiefvater, Maggie",
    "title": "Greywaren",
    "audience": "Juvenile fiction",
    "publicationDate": "1980",
    "summary": "Niall and Mór escaped their homeland for a new start, and lost themselves in what they found. Declan has grown up as the responsible son, the responsible brother only to find there is no way for him to keep his family safe.",
    "language": "English",
    "subject": "Dreams, Leys, Juvenile fiction, Dystopias",
    "rentalTimeInWeeks": "3"
}


### PUT material
PUT http://localhost:3000/materials/65b478f68a135779f5ddbdd5 HTTP/1.1
content-type: application/json

{
    "ISBN": "9781508287605",
    "format": "Audiobook",
    "author": "Kingsbury, Karen",
    "title": "The Baxters",
    "audience": "Adult fiction",
    "publicationDate": "2022",
    "summary": "itititititititititit.",
    "language": "English",
    "subject": "TESTit",
    "rentalTimeInWeeks": "1"
}


### DELETE material
DELETE http://localhost:3000/materials/65b48b8f5617c37461a3e507 HTTP/1.1





/////////////// P R O D U C T I O N ///////////////
///////////////////////////////////////////////////

// -----------------
// --  MATERIALS  --
// -----------------

### Get all materials
GET https://cse341-project2-ykx8.onrender.com/materials


### Get material by id
GET https://cse341-project2-ykx8.onrender.com/materials/65b1d0f6525bba6756f966f9


### Get material by format
GET https://cse341-project2-ykx8.onrender.com/materials/format/book


### Create material
POST https://cse341-project2-ykx8.onrender.com/materials HTTP/1.1
content-type: application/json

{
    "ISBN": "9781508287605",
    "format": "Audiobook",
    "author": "Kingsbury, Karen",
    "title": "The Baxters",
    "audience": "Adult fiction",
    "publicationDate": "2022",
    "summary": "A terrible storm builds in the morning sky over Bloomington, Indiana, as Elizabeth Baxter prepares to celebrate her daughter Kari's wedding to Tim Jacobs. It's supposed to be a happy day, but Elizabeth can't shake a growing sense of dread. Something bad is about to happen. Elizabeth knows it.",
    "language": "English",
    "subject": "Weddings, Man-woman relationships, Families, Omens, Bloomington",
    "rentalTimeInWeeks": "1 week"
}


### PUT material
PUT https://cse341-project2-ykx8.onrender.com/materials/65b1d0f6525bba6756f966f9 HTTP/1.1
content-type: application/json

{
    "ISBN": "9781508287605",
    "format": "Audiobook",
    "author": "Kingsbury, Karen",
    "title": "The Baxters",
    "audience": "Adult fiction",
    "publicationDate": "2022",
    "summary": "A terrible storm builds in the morning sky over Bloomington, Indiana, as Elizabeth Baxter prepares to celebrate her daughter Kari's wedding to Tim Jacobs. It's supposed to be a happy day, but Elizabeth can't shake a growing sense of dread. Something bad is about to happen. Elizabeth knows it.",
    "language": "English",
    "subject": "Weddings, Man-woman relationships, Families, Omens, Bloomington",
    "rentalTimeInWeeks": "1 week"
}


### DELETE material
DELETE https://cse341-project2-ykx8.onrender.com/materials/65b1d0f6525bba6756f966f9 HTTP/1.1